# Helper Entities Configuration
# Add these to your configuration.yaml or create via UI
# IMPORTANT: Create unique helpers for EACH room/automation

# Smart Mode Control Helpers
input_select:
  climate_control_mode_living_room:
    name: Climate Control Mode - Living Room
    options:
      - "Auto"      # Full automation with all features
      - "Manual"    # Keeps current settings, proximity safety only
      - "Smart"     # Auto with aggressive presence detection
    initial: "Auto"
    icon: mdi:robot

  climate_control_mode_bedroom:
    name: Climate Control Mode - Bedroom
    options:
      - "Auto"
      - "Manual"
      - "Smart"
    initial: "Auto"
    icon: mdi:robot

  climate_control_mode_office:
    name: Climate Control Mode - Office
    options:
      - "Auto"
      - "Manual"
      - "Smart"
    initial: "Auto"
    icon: mdi:robot

# Presence Tracking Helpers
input_datetime:
  presence_last_detected_living_room:
    name: Last Presence - Living Room
    has_date: true
    has_time: true
    icon: mdi:motion-sensor

  presence_last_detected_bedroom:
    name: Last Presence - Bedroom
    has_date: true
    has_time: true
    icon: mdi:motion-sensor

  presence_last_detected_office:
    name: Last Presence - Office
    has_date: true
    has_time: true
    icon: mdi:motion-sensor

# Emergency Override Helpers
input_boolean:
  climate_proximity_override_living_room:
    name: Proximity Override - Living Room
    initial: false
    icon: mdi:alert-circle

  climate_proximity_override_bedroom:
    name: Proximity Override - Bedroom
    initial: false
    icon: mdi:alert-circle

  climate_proximity_override_office:
    name: Proximity Override - Office
    initial: false
    icon: mdi:alert-circle

# Example for Living Room
input_text:
  climate_last_mode_living_room:
    name: Last Climate Mode - Living Room
    initial: "off"
    icon: mdi:air-conditioner
  
  climate_last_mode_bedroom:
    name: Last Climate Mode - Bedroom
    initial: "off"
    icon: mdi:air-conditioner
  
  climate_last_mode_office:
    name: Last Climate Mode - Office
    initial: "off"
    icon: mdi:air-conditioner

input_datetime:
  climate_last_change_living_room:
    name: Last Climate Change - Living Room
    has_date: true
    has_time: true
    icon: mdi:clock-outline
  
  climate_last_change_bedroom:
    name: Last Climate Change - Bedroom
    has_date: true
    has_time: true
    icon: mdi:clock-outline
  
  climate_last_change_office:
    name: Last Climate Change - Office
    has_date: true
    has_time: true
    icon: mdi:clock-outline
  
  # Dynamic Adaptation Mode Start Times
  climate_mode_start_time_living_room:
    name: Climate Mode Start - Living Room
    has_date: true
    has_time: true
    icon: mdi:timer-outline
  
  climate_mode_start_time_bedroom:
    name: Climate Mode Start - Bedroom  
    has_date: true
    has_time: true
    icon: mdi:timer-outline
  
  climate_mode_start_time_office:
    name: Climate Mode Start - Office
    has_date: true
    has_time: true
    icon: mdi:timer-outline

input_text:
  # Dynamic Adaptation Trend Tracking
  climate_trend_direction_living_room:
    name: Temperature Trend - Living Room
    initial: "stable"
    options:
      - "rising"
      - "falling"  
      - "stable"
    icon: mdi:trending-up
  
  climate_trend_direction_bedroom:
    name: Temperature Trend - Bedroom
    initial: "stable"
    options:
      - "rising"
      - "falling"
      - "stable"
    icon: mdi:trending-up
  
  climate_trend_direction_office:
    name: Temperature Trend - Office
    initial: "stable"
    options:
      - "rising"
      - "falling"
      - "stable"
    icon: mdi:trending-up

input_number:
  climate_power_saving_score:
    name: Climate Power Saving Score
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    icon: mdi:leaf
  
  # Dynamic Adaptation Temperature History
  climate_temp_history_living_room:
    name: Previous Temperature - Living Room
    min: -10
    max: 50
    step: 0.1
    unit_of_measurement: "°C"
    icon: mdi:thermometer-lines
  
  climate_temp_history_bedroom:
    name: Previous Temperature - Bedroom
    min: -10
    max: 50
    step: 0.1
    unit_of_measurement: "°C"  
    icon: mdi:thermometer-lines
  
  climate_temp_history_office:
    name: Previous Temperature - Office
    min: -10
    max: 50
    step: 0.1
    unit_of_measurement: "°C"
    icon: mdi:thermometer-lines
  
  # Dynamic Adaptation Effectiveness Scores
  climate_effectiveness_score_living_room:
    name: Climate Effectiveness - Living Room
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    icon: mdi:gauge
  
  climate_effectiveness_score_bedroom:
    name: Climate Effectiveness - Bedroom
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    icon: mdi:gauge
  
  climate_effectiveness_score_office:
    name: Climate Effectiveness - Office
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    icon: mdi:gauge

# Optional: Track energy usage
sensor:
  - platform: history_stats
    name: Climate Runtime Today
    entity_id: climate.living_room_air_conditioner_climate
    state: 
      - 'cool'
      - 'heat'
      - 'auto'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'

  - platform: template
    sensors:
      climate_efficiency_rating:
        friendly_name: "Climate Efficiency Rating"
        unit_of_measurement: "%"
        value_template: >
          {% set runtime = states('sensor.climate_runtime_today') | float(0) %}
          {% set cycles = state_attr('automation.ultimate_smart_climate_control', 'current') | int(0) %}
          {% if runtime > 0 %}
            {{ (100 - (cycles * 5)) | max(0) }}
          {% else %}
            100
          {% endif %}
        icon_template: >
          {% if states('sensor.climate_efficiency_rating') | float(0) > 80 %}
            mdi:leaf
          {% elif states('sensor.climate_efficiency_rating') | float(0) > 60 %}
            mdi:leaf-circle-outline
          {% else %}
            mdi:alert-circle-outline
          {% endif %}